format = 1

[package]
provenance = "built-in"
id = "org.mochios.edit"
name = "Edit"
version = "0.1.0"
revision = 1
vendor = "mochiOS"
kind = "application"
architecture = "x86_64"
abi = "mochios-1"

[application]
entry = "entry.elf"
description = "Plain text editor"
icon = "appicon.png"
resources = ["appicon.png"]
document_roles = ["view", "edit"]
document_content_types = [
    "text/plain",
    "application/json",
    "application/toml",
    "application/xml",
    "text/csv",
    "text/markdown",
    "text/x-c",
    "text/x-c++",
    "text/x-rust",
    "text/x-shellscript",
    "text/yaml",
]
document_extensions = [
    "txt", "text", "md", "markdown", "json", "toml", "xml", "csv",
    "yaml", "yml", "log", "ini", "conf", "cfg", "c", "h", "cc",
    "cpp", "cxx", "hh", "hpp", "rs", "sh",
]

[[application.control_center_items]]
id = "open-edit"
title = "Edit"
symbol = "pencil"
action = "open-application"

[[binary]]
path = "/system/applications/Edit.app/entry.elf"
kind = "application"
requires = [
    "ipc.client",
    "ipc.server",
    "window.create",
    "fs.read.user",
    "fs.write.user",
    "clipboard.read",
    "clipboard.write",
]
